# Created with YamlCreate.ps1 v2.4.1 $debug=QUSU.CRLF.7-4-6.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: WestWind.MarkdownMonster
PackageVersion: 3.5.3.0
Platform:
- Windows.Desktop
InstallerType: inno
Scope: machine
UpgradeBehavior: install
Commands:
- markdownmonster
- mm
- mmcli
FileExtensions:
- markdown
- md
- mdcrypt
- mdproj
- mkdown
Dependencies: 
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/RickStrahl/MarkdownMonsterReleases/raw/refs/heads/master/v3/v3.5/MarkdownMonsterSetup-3.5.3.exe
  InstallerSha256: DA21449B98A3B6A36E08C36AF3EF841A315817B706060FAA2E95F12CD7B72B38
ManifestType: installer
ManifestVersion: 1.6.0
